namespace Meow.Shared.DataAccess.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AutoGeneratedGuidKey : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Attendees", "EventId", "dbo.EventItems");
            DropPrimaryKey("dbo.Attendees");
            DropPrimaryKey("dbo.EventItems");
            AlterColumn("dbo.Attendees", "Id", c => c.Guid(nullable: false, identity: true, defaultValueSql: "newsequentialid()"));
            AlterColumn("dbo.EventItems", "Id", c => c.Guid(nullable: false, identity: true, defaultValueSql: "newsequentialid()"));
            AddPrimaryKey("dbo.Attendees", "Id");
            AddPrimaryKey("dbo.EventItems", "Id");
            AddForeignKey("dbo.Attendees", "EventId", "dbo.EventItems", "Id", cascadeDelete: true);
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.Attendees", "EventId", "dbo.EventItems");
            DropPrimaryKey("dbo.EventItems");
            DropPrimaryKey("dbo.Attendees");
            AlterColumn("dbo.EventItems", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Attendees", "Id", c => c.Guid(nullable: false));
            AddPrimaryKey("dbo.EventItems", "Id");
            AddPrimaryKey("dbo.Attendees", "Id");
            AddForeignKey("dbo.Attendees", "EventId", "dbo.EventItems", "Id", cascadeDelete: true);
        }
    }
}
