// <auto-generated />
namespace Meow.Shared.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AutoGeneratedGuidKey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AutoGeneratedGuidKey));
        
        string IMigrationMetadata.Id
        {
            get { return "201610230420012_AutoGeneratedGuidKey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
